apiVersion: v1
kind: Template
metadata:
  name: resource-cpu-memory
objects:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: dev
    spec:
      hard:
        requests.cpu: 1
        limits.cpu: 2
        requests.memory: 2Gi
        limits.memory: 4Gi
        requests.storage: 5Gi
        pods: 20
