apiVersion: v1
kind: Template
metadata:
  name: resource-cpu-memory
objects:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: stage
    spec:
      hard:
        requests.cpu: 2
        limits.cpu: 4
        requests.memory: 4Gi
        limits.memory: 8Gi
        requests.storage: 10Gi
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: cpu-defaults
    spec:
      limits:
        - type: Container
          default:
            cpu: 200m
          defaultRequest:
            cpu: 100m
